// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBywn1R4j5YgHdfyw7IehggkJYb_TqOUj4',
    appId: '1:998668364635:web:3f9bbffe38520b703f887e',
    messagingSenderId: '998668364635',
    projectId: 'new-todo-app-5d33f',
    authDomain: 'new-todo-app-5d33f.firebaseapp.com',
    storageBucket: 'new-todo-app-5d33f.appspot.com',
    measurementId: 'G-76CBJTGHG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Cn52n23-dQ-uwObUqYWjzfzELCsCIrg',
    appId: '1:998668364635:android:f4f460a2831e79b03f887e',
    messagingSenderId: '998668364635',
    projectId: 'new-todo-app-5d33f',
    storageBucket: 'new-todo-app-5d33f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaafqaNtlb3M5_pSfDpXCtBKBrH0zrV6I',
    appId: '1:998668364635:ios:35d2a586f8fb011f3f887e',
    messagingSenderId: '998668364635',
    projectId: 'new-todo-app-5d33f',
    storageBucket: 'new-todo-app-5d33f.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaafqaNtlb3M5_pSfDpXCtBKBrH0zrV6I',
    appId: '1:998668364635:ios:35d2a586f8fb011f3f887e',
    messagingSenderId: '998668364635',
    projectId: 'new-todo-app-5d33f',
    storageBucket: 'new-todo-app-5d33f.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBywn1R4j5YgHdfyw7IehggkJYb_TqOUj4',
    appId: '1:998668364635:web:984f81e71df05d4b3f887e',
    messagingSenderId: '998668364635',
    projectId: 'new-todo-app-5d33f',
    authDomain: 'new-todo-app-5d33f.firebaseapp.com',
    storageBucket: 'new-todo-app-5d33f.appspot.com',
    measurementId: 'G-FLSENC6F31',
  );

}